name: Configuration File Formatting

on:
  push:
  pull_request:

jobs:
  dapperdata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install Dependencies
        run: make install

      - name: Test Formatting
        run: make dapperdata_check
