name: Ruff Linting

on:
  push:
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version-file: .python-version

      - name: Install Dependencies
        run: make install

      - name: Test Formatting
        run: make ruff_check
